# Generated by Django 3.2.15 on 2022-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='avtive',
            field=models.BooleanField(default=True),
        ),
    ]
