# Generated by Django 3.2.15 on 2022-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_checkout_avtive'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='activ',
            field=models.BooleanField(default=True),
        ),
    ]
