# Generated by Django 3.2.15 on 2022-09-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_checkin_activ'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkin',
            table='checkin',
        ),
    ]
